"""Render drift results as a .env-style key=value flat file.

Useful for injecting drift metrics into shell scripts or CI pipelines
that source environment variables.
"""
from __future__ import annotations

from typing import Sequence

from drift_check.drift_detector import DriftItem, DriftKind


_KIND_PREFIX = {
    DriftKind.CHANGED: "CHANGED",
    DriftKind.MISSING_LIVE: "MISSING_LIVE",
    DriftKind.EXTRA_LIVE: "EXTRA_LIVE",
}


def _sanitize_key(value: str) -> str:
    """Replace non-alphanumeric characters with underscores for valid env keys."""
    return "".join(c if c.isalnum() else "_" for c in value).upper()


def render_dotenv(items: Sequence[DriftItem], *, source: str = "drift-check") -> str:
    """Return a .env-formatted string summarising drift results.

    Always emits summary counts.  Per-item lines are emitted for each
    DriftItem so callers can inspect individual resources.

    Args:
        items: Sequence of DriftItem instances from detect_drift().
        source: Identifies the tool; written into a comment header.

    Returns:
        A newline-terminated string of KEY=value pairs.
    """
    lines: list[str] = [
        f"# Generated by {source}",
        f"DRIFT_TOTAL={len(items)}",
        f"DRIFT_CHANGED={sum(1 for i in items if i.kind is DriftKind.CHANGED)}",
        f"DRIFT_MISSING_LIVE={sum(1 for i in items if i.kind is DriftKind.MISSING_LIVE)}",
        f"DRIFT_EXTRA_LIVE={sum(1 for i in items if i.kind is DriftKind.EXTRA_LIVE)}",
    ]

    for idx, item in enumerate(items):
        prefix = _KIND_PREFIX[item.kind]
        safe_id = _sanitize_key(item.resource_id)
        base = f"DRIFT_{prefix}_{safe_id}"
        lines.append(f"{base}_INDEX={idx}")
        lines.append(f"{base}_KIND={item.kind.value}")
        lines.append(f"{base}_RESOURCE_ID={item.resource_id}")
        if item.attribute:
            lines.append(f"{base}_ATTRIBUTE={item.attribute}")
        if item.expected is not None:
            lines.append(f"{base}_EXPECTED={item.expected}")
        if item.actual is not None:
            lines.append(f"{base}_ACTUAL={item.actual}")

    return "\n".join(lines) + "\n"
